//EJERCICIO 4: 
//REALIZAR  UN PROGRAMA QUE CALCULE EL SUELDO DE UN EMPLEADO, LAS VARIABLES DE INSTANCIA SON  ID_EMPLEADO, NOMBRE DEL EMPLEADO (CADENA),
//PUESTO (CADENA), SUELDO_QUINCENAL (ARREGLO UNIDIMENSIONAL). ELABORAR UN METODO QUE ACEPTE LOS DATOS INDICADOS SÓLO 
//SI CORRESPONDE CON EL PUESTO Y EL IDENTIFICADOR DEL EMPLEADO. ELABORAR OTRO METODO PARA CALCULAR EL TOTAL DE PAGO SEGÚN LO SIGUIENTE: 
//PARA EMPLEADOS SE CALCULARA EL SUELDO QUINCENAL (5000)+ HORAS EXTRAS DIURNAS ($50) Y HORAS EXTRAS NOCTURNAS ($60). 
//PARA EMPLEADOS SUPERVISORES SE CALCULARA SUELDO QUINCENAL(8000)-0.2% INFONAVIT -0.1%SEGURO DE GASTOS MEDICOS – 0.16%ISR

class Ejercicio4{
    public static void main(String []args){
        Metodos4 sergio = new Metodos4();

        sergio.Datos();
    }
} 